drop function if exists guided.register(text, text, text);
drop function if exists guided.authenticate(text, text);
drop function if exists guided."get_current_user"();
drop table if exists guided.rides;
drop table if exists guided.spots;
drop table if exists guided.guides;
drop table if exists guided.users;
-- drop owned by guided_postgraphile;
-- drop role if exists guided_postgraphile;
-- drop owned by guided_anonymous;
-- drop role if exists guided_anonymous;
-- drop owned by guided_user;
-- drop role if exists guided_user;
drop extension if exists "pgcrypto";
drop type if exists guided.jwt_token;
drop schema if exists guided;
create schema guided;
grant all privileges on schema guided to "postgres";
grant usage on schema guided to "postgres";