projects:
  guided:
    schemaPath: schema.json
    includes:
      - website/src/api/queries.ts
      - website/src/api/subscriptions.ts
      - website/src/api/mutations.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: website/src/api/generated.ts
        docsFilePath: amplify/graphql-docs
        maxDepth: 2
extensions:
  amplify:
    version: 3
