version: "3"

services:
  database:
    image: "postgres:11"
    container_name: "database"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
#    volumes:
#      - ./backend/data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./backend/data/redis:/data
    restart: always

  arena:
    container_name: worker-arena
    image: mixmaxhq/arena
    ports:
      - "4567:4567"
    volumes:
      - ./backend/data/arena.json:/opt/arena/src/api/config/index.json


  server:
    container_name: "api"
    build:
      context: backend/api
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "4000:4000"
    volumes:
      - ./backend/api:/app

  website:
    container_name: "website"
    build:
      context: frontend/website
      dockerfile: Dockerfile
    working_dir: /app
    command: './entrypoint.sh'
    ports:
      - "8000:8000"
    volumes:
      - ./frontend/website:/app
      - /app/node_modules/

  usersite:
    container_name: "usersite"
    build:
      context: frontend/usersite
      dockerfile: Dockerfile
    working_dir: /app
    command: './entrypoint.sh'
    ports:
      - "9000:9000"
    volumes:
      - ./frontend/usersite:/app
      - /app/node_modules/

