version: "3.5"

services:

  database:
    image: "postgres:11"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - ./graphql/data:/var/lib/postgresql/data

  graphql:
    image: graphile/postgraphile
    env_file:
      - ./graphql/.env.local
    volumes:
      - ./node_modules/@graphile/pg-pubsub/:/postgraphile/node_modules/@graphile/pg-pubsub/
      - ./node_modules/graphql-subscriptions/:/postgraphile/node_modules/graphql-subscriptions/
      - ./graphql/.postgraphilerc.js:/postgraphile/.postgraphilerc.js
    environment:
      - POSTGRAPHILE_HOST=0.0.0.0
    depends_on:
      - database
    ports:
      - "5000:5000"

volumes:
  database: