version: '2'
services:

  be_base:
    image: node:11
    volumes:
      - ./backend:/usr/src/backend
      - be_node_modules:/usr/src/backend/node_modules/
    working_dir: /usr/src/backend

  be_install:
    extends:
      service: be_base
    command: yarn install

  be_build:
    extends:
      service: be_base
    command: yarn build

  fe_install:
    image: node:11
    volumes:
      - ./frontend/website:/usr/src/frontend/website
      - fe_node_modules:/usr/src/frontend/website/node_modules/

    working_dir: /usr/src/frontend/website
    command: yarn install

  seed_basic:
    image: python:3.8-alpine
    volumes:
      - ./python/:/usr/src/python
    working_dir: /usr/src/python
    command: python3 guided seed basic

volumes:
  fe_node_modules:
  be_node_modules:
