service: compute-rides
app: guided
org: theostanton

provider:
  name: aws
  runtime: nodejs12.x
  stage: staging
  region: eu-west-2

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: ../../.env.staging
    logging: true

functions:
  compute:
    handler: srv/lambda.handler
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt:
              - computerides
              - Arn
    reservedConcurrency: 1


resources:
  Resources:
    computestage:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: compute-rides-staging