version: "3.5"

services:

  database:
    image: debezium/postgres
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=main
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"

#  goaws:
#    image: pafortin/goaws
#    ports:
#      - "4100:4100"

#  graphql:
#    image: graphile/postgraphile
#    env_file:
#      - ./graphql/.env.local
#    volumes:
#      - ./plugins/:/postgraphile/plugins/
#      - ./graphql/.postgraphilerc.js:/postgraphile/.postgraphilerc.js
#    environment:
#      - POSTGRAPHILE_HOST=0.0.0.0
#      - WORK_DIR=/postgraphile
#    depends_on:
#      - database
#    ports:
#      - "5000:5000"

volumes:
  database: