service: custom-sites
app: custom-sites
org: floom

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
  fetch-products:
    handler: src/fetch-products.handler
    events:
      - http:
          method: get
          path: fetch-products
          cors: true
  check-postcode:
    handler: src/fetch-products.handler
    events:
      - http:
          method: get
          path: check-postcode
          cors: true
