# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: graphql-server
# app and org for use with dashboard.serverless.com
app: guided
org: theostanton

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
  stage: staging
  region: eu-west-2
  deploymentBucket:
    name: guided-graphql-deployment

  package:
    exclude:
      - src/**

plugins:
  - serverless-content-encoding
  - serverless-dotenv-plugin

custom:
  contentEncoding:
    minimumCompressionSize: 0
  dotenv:
    path: ../../.env.staging
    logging: true

package:
  individually: false

functions:
  graphql:
    handler: srv/lambda.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
          integration: lambda-proxy
