version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19
  terraform: ngs/terraform@0.0.1
  shellcheck: circleci/shellcheck@1.3.15


commands:
  test:
    steps:
      - run:
          name: "Test"
          environment:
            TEST_DATABASE_URL: 'postgresql://root@localhost/circle_test'
          command: |
            cd backend
            yarn test:all

      - store_artifacts:
          path: ~workspace/backend/reports/junit
      - store_test_results:
          path: ~workspace/backend/reports/junit

jobs:
  tests:
    working_directory: ~/workspace
    environment:
      - STAGE: test
      - DATABASE_URL: postgresql://postgres@localhost/circle_test
    docker:
      - image: circleci/node:12.9.1
      - image: circleci/postgres:9.6-alpine-ram
    steps:
      - checkout
      - run:
          name: Run tests
          command: yarn test:all
      - store_artifacts:
          path: ~workspace/reports/junit
      - store_test_results:
          path: ~workspace/reports/junit

  deploy-frontend:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: "Install terraform"
          command: |
            cd deploy
            sudo  sh ./scripts/install_terraform.sh
      - run:
          name: "Init terraform"
          command: |
            cd deploy
            terraform init
      - run:
          name: "Install dependencies"
          command: |
            cd frontend/website
            yarn install

      - run:
          name: "Deploy and Deploy"
          command: |
            cd deploy
            export BUILD=true
            export DEPLOY=true
            chmod +x ./scripts/deploy.frontend.sh
            ./scripts/deploy.frontend.sh

  deploy-backend:
    executor: aws-cli/default
    docker:
      - image: circleci/golang:1.14
      - image: circleci/node:12.9.1
    working_directory: ~/workspace
    steps:
      - aws-cli/setup
      - checkout
      - add_ssh_keys
      - run:
          name: "Go version"
          command: |
            echo GOROOT
            echo $GOROOT
            echo GOPATH
            echo $GOPATH
            which go
            go version
      - run:
          name: "Install terraform"
          command: |
            cd deploy
            sudo sh ./scripts/install_terraform.sh

      - run:
          name: "Install dependencies"
          command: |
            cd backend
            yarn install

      - run:
          name: "Init terraform"
          command: |
            cd deploy
            terraform init

      - run:
          name: "Lint"
          command: |
            cd backend
            yarn lint

      - run:
          name: "Build"
          environment:
            BUILD: 'true'
            DEPLOY: 'false'
          command: |
            cd deploy
            chmod +x ./scripts/deploy.backend.sh
            ./scripts/deploy.backend.sh

      - run:
          name: "Test"
          command: |
            cd backend
            yarn test:all

      - run:
          name: "Deploy"
          environment:
            BUILD: 'false'
            DEPLOY: 'true'
          command: |
            cd deploy
            chmod +x ./scripts/deploy.backend.sh
            ./scripts/deploy.backend.sh

workflows:
  version: 2

  Deploy Staging backend:
    jobs:
      - deploy-backend:
          context: guided-staging
          filters:
            branches:
              only: staging

  Deploy Staging frontend:
    jobs:
      - deploy-frontend:
          context: guided-staging
          filters:
            branches:
              only: staging

  Deploy Production:
    jobs:
      - shellcheck/check:
          filters:
            branches:
              only: master
      - deploy-backend:
          context: guided-production
          requires:
            - shellcheck/check
      - deploy-frontend:
          context: guided-production
          requires:
            - deploy-backend
