version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19

commands:
  install:
    description: "Install"
    parameters:
      directory:
        type: string
    steps:
      - run: |
          cd << parameters.directory >>
          yarn install
  build:
    description: "Build"
    parameters:
      directory:
        type: string
    steps:
      - run: |
          cd << parameters.directory >>
          yarn build
  deploy:
    description: "Deploy"
    parameters:
      directory:
        type: string
    steps:
      - run: |
          cd << parameters.directory >>
          yarn deploy


jobs:
  deploy-graphql-staging:
    docker:
      - image: circleci/node:latest

    working_directory: ~/graphql

    steps:
      - checkout
      - aws-cli/setup
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/server/package.json" }}

      - install:
          directory: backend/server

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "website/package.json" }}

      - build:
          directory: backend/server

      - deploy:
          directory: backend/server

  deploy-graphql-production:
    docker:
      - image: circleci/node:latest

    working_directory: ~/graphql

    steps:
      - checkout
      - aws-cli/setup
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/server/package.json" }}

      - install:
          directory: backend/server

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "website/package.json" }}

      - build:
          directory: backend/server

      - deploy:
          directory: backend/server

  deploy-website-staging:
    docker:
      - image: circleci/node:latest

    working_directory: ~/website

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "website/package.json" }}

      - install:
          directory: website

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "website/package.json" }}

      - build:
          directory: website

      - deploy:
          directory: website

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "website/package.json" }}

  deploy-website-production:
    docker:
      - image: circleci/node:latest

    working_directory: ~/website

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "website/package.json" }}

      - install:
          directory: website

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "website/package.json" }}

      - build:
          directory: website

      - deploy:
          directory: website

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "website/package.json" }}

workflows:
  version: 2
  Deploy Staging:
    filters:
      branches:
        only: staging
    jobs:
    - deploy-graphql-staging:
        context: guided-staging
        filters:
          branches:
            only: master

    - deploy-website-staging:
        context: guided-staging
        filters:
          branches:
            only: master
        requires:
          - deploy-graphql-staging

  Deploy Production:
    jobs:
      - deploy-graphql-production:
          context: guided-production
          filters:
            branches:
              only: master

      - deploy-website-production:
          context: guided-production
          filters:
            branches:
              only: master
          requires:
            - deploy-graphql-production