version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19

commands:
  build:
    description: "Build"
    steps:
      - run: yarn build
  deploy:
    description: "Deploy"
    steps:
      - run: yarn deploy


jobs:
  prepare:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: node_modules
      - run:
          name: "Install"
          command: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: node_modules-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths: .

  build-graphql-staging:
    docker:
      - image: circleci/node:latest

    working_directory: ~/workspace/backend/server
    steps:
      - attach_workspace:
          at: ~/workspace
      - build

  deploy-graphql-staging:
    docker:
      - image: circleci/node:latest
    working_directory: ~/workspace/backend/server
    steps:
      - attach_workspace:
          at: ~/workspace
      - deploy

  deploy-graphql-production:
    docker:
      - image: circleci/node:latest
    working_directory: ~/workspace/backend/server

    steps:
      - aws-cli/setup
      - attach_workspace:
          at: ~/workspace

      - build
      - deploy

  build-website-staging:
    docker:
      - image: circleci/node:latest

    working_directory: ~/workspace/website

    steps:
      - attach_workspace:
          at: ~/workspace
      - build

  deploy-website-staging:
    docker:
      - image: circleci/node:latest

    working_directory: ~/workspace/website

    steps:
      - attach_workspace:
          at: ~/workspace
      - deploy

  deploy-website-production:
    docker:
      - image: circleci/node:latest

    working_directory: ~/workspace/website
    steps:
      - attach_workspace:
          at: ~/workspace
      - build
      - deploy

workflows:
  version: 2
  Deploy Staging:
    jobs:
      - prepare:
          filters:
            branches:
              only: staging

      - build-graphql-staging:
          context: guided-staging
          requires:
            - prepare

      - deploy-graphql-staging:
          context: guided-staging
          requires:
            - build-graphql-staging

      - build-website-staging:
          context: guided-staging
          requires:
            - prepare

      - deploy-website-staging:
          context: guided-staging
          requires:
            - build-website-staging
            - deploy-graphql-staging

  Deploy Production:
    jobs:
      - prepare:
          filters:
            branches:
              only: master
      - deploy-graphql-production:
          context: guided-production
          requires:
            - prepare

      - deploy-website-production:
          context: guided-production
          requires:
            - prepare
            - deploy-graphql-production