version: 2.1
jobs:
  deploy-website:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Set directory
          command: cd website
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: PWD
          command: pwd
      - run:
          name: List
          command: ls -la
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy
          command: yarn deploy

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  Deploy-Website:
    jobs:
      - deploy-website