version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19

commands:
  deploy:
    description: "Deploy"
    steps:
      - run: yarn deploy
  test:
    parameters:
      directory:
        type: string
    steps:
      - run:
          name: Test << parameters.directory >>
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit/"
          command: |
            cd << parameters.directory >>
      #            yarn test --passWithNoTests --ci --reporters=default --reporters=jest-junit
      - store_artifacts:
          path: << parameters.directory >>/reports/junit
      - store_test_results:
          path: << parameters.directory >>/reports/junit

  build:
    description: "Build"
    parameters:
      directory:
        type: string
    steps:
      - run:
          name: Build << parameters.directory >>
          command: |
            cd ~/workspace/<< parameters.directory >>
            yarn build


jobs:
  tests:
    working_directory: ~/workspace
    environment:
      - STAGE: test
      - DATABASE_URL: postgresql://postgres@localhost/circle_test
    docker:
      - image: circleci/node:12.9.1
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          POSTGRES_USER: postgres
    steps:
      - run:
          name: Run tests
          command: yarn test:all
      - store_artifacts:
          path: ~workspace/reports/junit
      - store_test_results:
          path: ~workspace/reports/junit
  prepare:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.9.1
    steps:
      - checkout
      - restore_cache:
          key: node_modules
      - run:
          name: "Install"
          command: yarn install
      - run:
          name: "Build"
          command: yarn build
      - save_cache:
          paths:
            - ./node_modules
          key: node_modules-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths: .

  deploy-compute-stage-staging:
    environment:
      - STAGE: staging
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/workspace/events/compute-stage
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Build
          command: yarn build
      - test:
          directory: ~/workspace/events/compute-stage
      - deploy

  deploy-staging:
    environment:
      - STAGE: staging
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/workspace/backend/graphql
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Build
          command: yarn build
      - test:
          directory: ~/workspace/backend/graphql
      - run:
          name: Deploy
          command: yarn workspace @guided/deploy run deploy:staging

workflows:
  version: 2
  Deploy Staging:
    jobs:
      - prepare:
          filters:
            branches:
              only: staging

      - tests:
          requires:
            - prepare

      - deploy-staging:
          requires:
            - tests
