version: 2.1
jobs:
  deploy-website:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/website

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
            cd website
            yarn install
      - run:
          name: Build
          command: |
            cd website
            yarn build
      - run:
          name: Deploy
          command: |
            cd website
            yarn deploy

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  Deploy-Website:
    jobs:
      - deploy-website