version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19

commands:
  build:
    description: "Build"
    parameters:
      directory:
        type: string
    steps:
      - run: |
          cd << parameters.directory >>
          yarn build
  deploy:
    description: "Deploy"
    parameters:
      directory:
        type: string
    steps:
      - run: |
          cd << parameters.directory >>
          yarn deploy


jobs:

  prepare:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key:
            - key-{{ checksum "yarn.lock" }}
      - aws-cli/setup
      - run:
          name: "Build tools"
          command: |
            cd backend/tools
            yarn install
      - save_cache:
          paths:
            - ./node_modules
            - ./backend/codegen/node_modules
            - ./backend/server/node_modules
            - ./backend/spinup/node_modules
            - ./backend/tools/node_modules
            - ./backend/tools/srv
            - ./website/node_modules
          key:
            - key-{{ checksum "lock.json" }}


  deploy-graphql-staging:
    docker:
      - image: circleci/node:latest

    working_directory: ~/graphql

    steps:
      - checkout
      - aws-cli/setup
      - restore_cache:
          key:
            - key-{{ checksum "yarn.lock" }}

      - build:
          directory: backend/server

      - deploy:
          directory: backend/server

  deploy-graphql-production:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - aws-cli/setup
      - restore_cache:
          key:
            - key-{{ checksum "yarn.lock" }}

      - build:
          directory: backend/server

      - deploy:
          directory: backend/server

  deploy-website-staging:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - restore_cache:
          key:
            - key-{{ checksum "yarn.lock" }}

      - build:
          directory: website

      - deploy:
          directory: website

  deploy-website-production:
    docker:
      - image: circleci/node:latest

    working_directory: ~/website

    steps:
      - checkout
      - restore_cache:
          key:
            - key-{{ checksum "yarn.lock" }}

      - build:
          directory: website

      - deploy:
          directory: website

workflows:
  version: 2
  Deploy Staging:
    jobs:
      - prepare:
          filters:
            branches:
              only: staging
      - deploy-graphql-staging:
          context: guided-staging
          requires:
            - prepare

      - deploy-website-staging:
          context: guided-staging
          requires:
            - prepare
            - deploy-graphql-staging

  Deploy Production:
    jobs:
      - prepare:
          filters:
            branches:
              only: master
      - deploy-graphql-production:
          context: guided-production
          requires:
            - prepare

      - deploy-website-production:
          context: guided-production
          requires:
            - prepare
            - deploy-graphql-production