version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19

commands:
  deploy:
    description: "Deploy"
    steps:
      - run: yarn deploy

jobs:
  prepare-backend:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          key: node_modules
      - run:
          name: "Install"
          command: |
            cd backend
            yarn install
      - save_cache:
          paths:
            - ./backend/node_modules
          key: node_modules-backend-{{ checksum "backend/yarn.lock" }}
      - run:
          name: "Transpile"
          command: |
            cd backend
            yarn build

workflows:
  version: 2
  Deploy Staging:
    jobs:
      - prepare-backend:
          filters:
            branches:
              only: staging