version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19
  terraform: ngs/terraform@0.0.1

jobs:
  deploy-frontend:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: "Install terraform"
          command: |
            cd deploy
            sudo  sh ./install_terraform.sh
      - run:
          name: "Init terraform"
          command: |
            cd deploy
            terraform init
      - run:
          name: "Install"
          command: |
            cd frontend/website
            yarn install
            yarn install
      - run:
          name: "Build and deploy"
          command: |
            cd deploy
            yarn deploy:frontend:staging

  deploy-backend:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/workspace
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: "Install terraform"
          command: |
            cd deploy
            sudo  sh ./install_terraform.sh
      - run:
          name: "Install dependencies"
          command: |
            cd backend
            yarn install
      - run:
          name: "Init"
          command: |
            cd deploy
            terraform init

      #      - run:
      #          name: "Build"
      #          command: |
      #            cd deploy
      #            yarn build:backend:staging

      - run:
          name: "Build and deploy"
          environment:
            TF_VAR_private_key_path: /home/circleci/.ssh/id_rsa_5eab1ebe72710affd8434c2c6e2f82e0
          command: |
            cd deploy
            yarn buildAndDeploy:backend:staging

#      - run:
#          name: "Deploy"
#          no_output_timeout: 30m
#          command: |
#            cd deploy
#            terraform apply -var macro_version=${CIRCLE_BUILD_NUM} -auto-approve


workflows:
  version: 2
  Deploy Staging:
    jobs:
      - deploy-backend:
          context: guided-staging
          filters:
            branches:
              only: staging
      - deploy-frontend:
          requires:
            - deploy-backend
