version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19
  terraform: ovotech/terraform@1.6.5

jobs:
  deploy-backend:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/workspace/
    steps:
      - checkout
      - restore_cache:
          key: node_modules-backend
      - run:
          name: "Install"
          command: |
            cd backend
            yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: node_modules-backend-{{ checksum "yarn.lock" }}
      - run:
          name: "Prepare"
          command: |
            cd deploy
            yarn deploy:backend:staging
      - terraform/apply:
          name: "Apply"
          environment:
            TF_VAR_db_owner_user: $OWNER_USER
            TF_VAR_db_owner_password: $OWNER_PASSWORD
            TF_VAR_db_postgraphile_user: $POSTGRES_USER
            TF_VAR_db_postgraphile_password: $POSTGRES_PASSWORD
            TF_VAR_jwt_secret: $JWT_SECRET
          path: deploy
          workspace: staging

workflows:
  version: 2
  Deploy Staging:
    jobs:
      - deploy-backend:
          context: guided-staging
          filters:
            branches:
              only: staging