version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19
  terraform: ngs/terraform@0.0.1

jobs:
  deploy-backend:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/workspace/deploy
    environment:
      TF_VAR_db_owner_user: $OWNER_USER
      TF_VAR_db_owner_password: $OWNER_PASSWORD
      TF_VAR_db_postgraphile_user: $POSTGRES_USER
      TF_VAR_db_postgraphile_password: $POSTGRES_PASSWORD
      TF_VAR_jwt_secret: $JWT_SECRET
    steps:
      - checkout
      - restore_cache:
          key: node_modules-backend
      - run:
          name: "Install terraform"
          command:
            - sh ./install_terraform.sh
      - run:
          name: "Install"
          command: |
            cd ../backend
            yarn install
      - save_cache:
          paths:
            - ../backend/node_modules
          key: node_modules-backend-{{ checksum "yarn.lock" }}
      - run:
          name: "Prepare"
          command: |
            cd ../deploy
            yarn deploy:backend:staging


workflows:
  version: 2
  Deploy Staging:
    jobs:
      - deploy-backend:
          context: guided-staging
          filters:
            branches:
              only: staging
      - terraform/apply:
          path: deploy
          workspace: staging