version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19
  terraform: ngs/terraform@0.0.1

jobs:
  deploy-backend:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/workspace
    environment:
      TF_VAR_stage: STAGE
      TF_VAR_db_owner_user: $OWNER_USER
      TF_VAR_db_owner_password: $OWNER_PASSWORD
      TF_VAR_db_postgraphile_user: $POSTGRES_USER
      TF_VAR_db_postgraphile_password: $POSTGRES_PASSWORD
      TF_VAR_jwt_secret: $JWT_SECRET
    steps:
      - checkout
      - restore_cache:
          key: backend
      - run:
          name: "Install terraform"
          command: |
            cd deploy
            chmod +x ./install_terraform.sh
            sudo  sh ./install_terraform.sh
      - run:
          name: "Install"
          command: |
            cd backend
            yarn install
      - save_cache:
          paths:
            - backend/node_modules
          key: backend-{{ checksum "yarn.lock" }}
      - run:
          name: "Build"
          command: |
            cd deploy
            yarn deploy:backend:staging
      - run:
          name: "Init"
          command: |
            cd deploy
            terraform workspace select staging
            terraform init
      - run:
          name: "Deploy"
          command: |
            cd deploy
            terraform workspace select staging
            terraform apply -var macro_version=0 -auto-approve


workflows:
  version: 2
  Deploy Staging:
    jobs:
      - deploy-backend:
          context: guided-staging
          filters:
            branches:
              only: staging