version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19

jobs:
  deploy-backend:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/workspace/
    steps:
      - checkout
      - restore_cache:
          key: node_modules-backend
      - run:
          name: "Install"
          command: |
            cd backend
            yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: node_modules-backend-{{ checksum "yarn.lock" }}
      - run:
          name: "Deploy"
          command: |
            cd deploy
            yarn deploy:backend:staging

workflows:
  version: 2
  Deploy Staging:
    jobs:
      - deploy-backend:
          context: guided-staging
          filters:
            branches:
              only: staging