version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19

commands:
  deploy:
    description: "Deploy"
    steps:
      - run: yarn deploy

jobs:
  prepare-backend:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/workspace/backend
    steps:
      - checkout
      - restore_cache:
          key: node_modules
      - run:
          name: "Install"
          command: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: node_modules-backend-{{ checksum "yarn.lock" }}
      - run:
          name: "Transpile"
          command: yarn build
  build-compute:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/workspace/backend/elements/compute
    parameters:
      filename:
        type: string
        default: << pipeline.git.branch	>>-<< pipeline.number >>-compute.zip"
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: "Pack"
          command: yarn webpack
      - run:
          name: "Filename"
          command: echo << parameters.filename >>
      - run:
          name: "Zip"
          command: zip -rj ../../../deploy/<< parameters.filename >> dist

workflows:
  version: 2
  Deploy Staging:
    jobs:
      - prepare-backend:
          filters:
            branches:
              only: staging