version: "3"
services:
  #  Create a service named db.
  database:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres:11"
    #   Give the container the name my_postgres. You can changes to something else.
    container_name: "guided_db"
    #   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "54320:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
