#org: theostanton
#app: guided
service: ${env:_AWS_SERVICE_NAME}

plugins:
  - serverless-content-encoding

custom:
  contentEncoding:
    minimumCompressionSize: 0

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  deploymentBucket:
    name: ${env:_AWS_SERVICE_NAME}
  region: ${env:_AWS_REGION}
  stage: ${env:_AWS_STAGE}

functions:
  graphql:
    handler: index.handler # Actual handler substituted in during deploy script
    events:
      - http:
          method: post
          path: graphql
          cors: true
          integration: lambda-proxy
    environment:
      DATABASE_URL: ${env:DATABASE_URL}
      DATABASE_SCHEMAS: ${env:DATABASE_SCHEMAS}
#      JWT_SECRET: ${env:JWT_SECRET}
#      JWT_PG_TYPE_IDENTIFIER: ${env:JWT_PG_TYPE_IDENTIFIER}
