version: "3"

services:

  database:
    image: "postgres:11"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - ./backend/data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379"
