export type SpotStatus = "complete" | "ready" | "computing" | "stale"
export type StageStatus = "complete" | "ready" | "computing" | "stale"
export type RideStatus = "complete" | "ready" | "stale"
export type ComputationStatus = "scheduled" | "failed" | "computing" | "success"

/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface Computation {
  id: string
  ended: any | null
  duration: number | null
  status: ComputationStatus
  stage: string | null
  guide: string
  created: any
  started: any | null
}

export interface Guide {
  id: string
  title: string
  slug: string
  owner: string
  start_date: string | null
  max_hours_per_ride?: number
  created: any
  updated: any | null
}

export interface Ride {
  id: string
  guide: string
  owner: string
  from_spot: string
  to_spot: string
  path_url: string | null
  duration_seconds: number | null
  distance_meters: number | null
  date: string | null
  stage: string
  position: string | null
  status: RideStatus
  created: any
  updated: any | null
}

export interface Spot {
  id: string
  label: string | null
  guide: string
  owner: string
  nights?: number | null
  locked: boolean
  lat: number
  long: number
  position: string | null
  location: string | null
  country: string | null
  date: string | null
  created: any
  updated: any | null
  stage: string | null
}

export interface Stage {
  id: string
  guide: string
  from_spot: string
  to_spot: string
  created: any
  updated: any | null
  status: StageStatus
  position: number | null
}

export interface Temperature {
  id: string
  country: string
  month: number
  temperature: number
  created: any
  updated: any | null
}

export interface User {
  username: string
  email: string
  password_hash: string
  created: any
  updated: any | null
}
