"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var GuidesOrderBy;
(function (GuidesOrderBy) {
    GuidesOrderBy["Natural"] = "NATURAL";
    GuidesOrderBy["IdAsc"] = "ID_ASC";
    GuidesOrderBy["IdDesc"] = "ID_DESC";
    GuidesOrderBy["TitleAsc"] = "TITLE_ASC";
    GuidesOrderBy["TitleDesc"] = "TITLE_DESC";
    GuidesOrderBy["SlugAsc"] = "SLUG_ASC";
    GuidesOrderBy["SlugDesc"] = "SLUG_DESC";
    GuidesOrderBy["OwnerAsc"] = "OWNER_ASC";
    GuidesOrderBy["OwnerDesc"] = "OWNER_DESC";
    GuidesOrderBy["StartDateAsc"] = "START_DATE_ASC";
    GuidesOrderBy["StartDateDesc"] = "START_DATE_DESC";
    GuidesOrderBy["PrimaryKeyAsc"] = "PRIMARY_KEY_ASC";
    GuidesOrderBy["PrimaryKeyDesc"] = "PRIMARY_KEY_DESC";
})(GuidesOrderBy = exports.GuidesOrderBy || (exports.GuidesOrderBy = {}));
var RidesOrderBy;
(function (RidesOrderBy) {
    RidesOrderBy["Natural"] = "NATURAL";
    RidesOrderBy["IdAsc"] = "ID_ASC";
    RidesOrderBy["IdDesc"] = "ID_DESC";
    RidesOrderBy["GuideAsc"] = "GUIDE_ASC";
    RidesOrderBy["GuideDesc"] = "GUIDE_DESC";
    RidesOrderBy["FromSpotAsc"] = "FROM_SPOT_ASC";
    RidesOrderBy["FromSpotDesc"] = "FROM_SPOT_DESC";
    RidesOrderBy["ToSpotAsc"] = "TO_SPOT_ASC";
    RidesOrderBy["ToSpotDesc"] = "TO_SPOT_DESC";
    RidesOrderBy["PrimaryKeyAsc"] = "PRIMARY_KEY_ASC";
    RidesOrderBy["PrimaryKeyDesc"] = "PRIMARY_KEY_DESC";
})(RidesOrderBy = exports.RidesOrderBy || (exports.RidesOrderBy = {}));
var SpotsOrderBy;
(function (SpotsOrderBy) {
    SpotsOrderBy["Natural"] = "NATURAL";
    SpotsOrderBy["IdAsc"] = "ID_ASC";
    SpotsOrderBy["IdDesc"] = "ID_DESC";
    SpotsOrderBy["LabelAsc"] = "LABEL_ASC";
    SpotsOrderBy["LabelDesc"] = "LABEL_DESC";
    SpotsOrderBy["GuideAsc"] = "GUIDE_ASC";
    SpotsOrderBy["GuideDesc"] = "GUIDE_DESC";
    SpotsOrderBy["NightsAsc"] = "NIGHTS_ASC";
    SpotsOrderBy["NightsDesc"] = "NIGHTS_DESC";
    SpotsOrderBy["LockedAsc"] = "LOCKED_ASC";
    SpotsOrderBy["LockedDesc"] = "LOCKED_DESC";
    SpotsOrderBy["PrimaryKeyAsc"] = "PRIMARY_KEY_ASC";
    SpotsOrderBy["PrimaryKeyDesc"] = "PRIMARY_KEY_DESC";
})(SpotsOrderBy = exports.SpotsOrderBy || (exports.SpotsOrderBy = {}));
var UsersOrderBy;
(function (UsersOrderBy) {
    UsersOrderBy["Natural"] = "NATURAL";
    UsersOrderBy["UsernameAsc"] = "USERNAME_ASC";
    UsersOrderBy["UsernameDesc"] = "USERNAME_DESC";
    UsersOrderBy["EmailAsc"] = "EMAIL_ASC";
    UsersOrderBy["EmailDesc"] = "EMAIL_DESC";
    UsersOrderBy["PasswordHashAsc"] = "PASSWORD_HASH_ASC";
    UsersOrderBy["PasswordHashDesc"] = "PASSWORD_HASH_DESC";
    UsersOrderBy["PrimaryKeyAsc"] = "PRIMARY_KEY_ASC";
    UsersOrderBy["PrimaryKeyDesc"] = "PRIMARY_KEY_DESC";
})(UsersOrderBy = exports.UsersOrderBy || (exports.UsersOrderBy = {}));
