/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface Guide {
  id: string 
  title: string 
  slug: string 
  owner: string 
  start_date: Date | null 
  max_hours_per_ride?: number 
}
export interface Ride {
  id: string 
  guide: string 
  owner: string 
  from_spot: string 
  to_spot: string 
  path: Object | null 
  duration_seconds: number | null 
  distance_meters: number | null 
  date: Date | null 
  stage: string 
}
export interface Spot {
  id: string 
  label: string | null 
  guide: string 
  owner: string 
  nights?: number | null 
  locked: boolean 
  lat: number 
  long: number 
  position: string | null 
  location: string | null 
  country: string | null 
  date: Date | null 
  stage: string | null 
}
export interface Stage {
  id: string 
  guide: string 
  from_spot: string 
  to_spot: string 
}
export interface User {
  username: string 
  email: string 
  password_hash: string 
}
