/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface Guide {
  id: string 
  title: string 
  slug: string 
  owner: string 
  startDate: Date | null 
}
export interface Ride {
  id: string 
  guide: string 
  owner: string 
  fromSpot: string 
  toSpot: string 
}
export interface Spot {
  id: string 
  label: string | null 
  guide: string 
  owner: string 
  nights: number | null 
  locked: boolean | null 
  lat: number | null 
  long: number | null 
}
export interface User {
  username: string 
  email: string 
  passwordHash: string 
}
